#! /usr/bin/env bash
set -euo pipefail

rm -rf build/distributions/*
./gradlew generateIixJooqSchemaSource
./gradlew distTar

docker build -t loll3k/spark-backend -t loll3k/spark-backend:$(date "+%Y-%m-%d") .
