#! /usr/bin/env bash
set -euo pipefail

die() {
  echo $@
  exit 1
}

[[ -z ${DBPATH} ]] && die "Environment variable DBPATH missing"
[[ -z ${DBUSER} ]] && die "Environment variable DBUSER missing"
[[ -z ${DBPASSWORD} ]] && die "Environment variable DBPASSWORD missing"
[[ -z ${DBPASSWORD} ]] && die "Environment variable GOODREADS_KEY missing"
[[ -z ${JWT} ]] && die "Environment variable JWT missing"

export SPARK_BACKEND_OPTS="-DdbPath=${DBPATH} \
  -DdbUser=${DBUSER} \
  -DdbPassword=${DBPASSWORD} \
  -DgoodreadsApiKey=${GOODREADS_KEY} \
  -Djwt=${JWT}"

exec /app/bin/spark-backend
