#! /usr/bin/env bash
set -euo pipefail

cd ../iix.se-frontend-angular
git ff
npm run dist
cd -

git ff
rm -rf build/distributions/*
./gradlew distTar

tar xf build/distributions/spark-backend-0.1.tar
sed -i 's/exec /exec authbind /' spark-backend-0.1/bin/spark-backend

rm -rf dist/{bin,lib}
mv spark-backend-0.1/{bin,lib} dist
rmdir spark-backend-0.1

sudo systemctl restart spark-backend
